# Production Environment Configuration
# QuantumFlux Trading Platform

app:
  name: "QuantumFlux Trading Platform"
  version: "2.0.0"
  environment: "production"
  debug: false
  log_level: "INFO"

api:
  host: "0.0.0.0"
  port: 8000
  reload: false
  workers: 4
  cors_origins:
    - "https://your-frontend-domain.com"
  rate_limiting:
    enabled: true
    default_limit: 1000
    default_window: 60

database:
  type: "postgresql"
  url: "${DATABASE_URL}"
  echo: false
  pool_size: 20
  max_overflow: 30
  ssl_require: true

trading:
  platform: "pocket_option"
  demo_mode: false
  default_stake_amount: 50.0
  max_concurrent_trades: 5
  max_daily_trades: 100
  risk_management:
    max_risk_per_trade: 0.01  # 1% of account
    max_daily_risk: 0.05      # 5% of account
    stop_loss_enabled: true
    take_profit_enabled: true

market_data:
  providers:
    primary: "pocket_option_websocket"
    fallback: "pocket_option_rest"
  cache:
    enabled: true
    ttl_seconds: 10
    redis_url: "${REDIS_URL}"
  real_time:
    enabled: true
    buffer_size: 5000
    update_interval_ms: 50

strategy:
  default_timeframe: "1m"
  signal_strength_threshold: "STRONG"
  backtest:
    enabled: true
    initial_balance: 50000.0
    commission: 0.001
  validation:
    min_historical_data_points: 500
    required_indicators:
      - "rsi"
      - "macd"
      - "bollinger_bands"
      - "stochastic"
      - "atr"

webdriver:
  browser: "chrome"
  headless: true
  implicit_wait: 5
  page_load_timeout: 15
  window_size:
    width: 1920
    height: 1080
  options:
    - "--headless"
    - "--no-sandbox"
    - "--disable-dev-shm-usage"
    - "--disable-gpu"
    - "--disable-extensions"
    - "--disable-blink-features=AutomationControlled"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    console:
      enabled: false
      level: "ERROR"
    file:
      enabled: true
      level: "INFO"
      path: "/var/log/quantumflux/app.log"
      max_bytes: 52428800  # 50MB
      backup_count: 10
    trading:
      enabled: true
      level: "INFO"
      path: "/var/log/quantumflux/trades.log"
      max_bytes: 52428800
      backup_count: 20
    syslog:
      enabled: true
      level: "WARNING"
      facility: "local0"

monitoring:
  metrics:
    enabled: true
    port: 9090
    prometheus_endpoint: "/metrics"
  health_check:
    enabled: true
    endpoint: "/health"
    interval_seconds: 10
  alerts:
    enabled: true
    email_notifications: true
    smtp_server: "${SMTP_SERVER}"
    smtp_port: 587
    smtp_username: "${SMTP_USERNAME}"
    smtp_password: "${SMTP_PASSWORD}"
    webhook_url: "${ALERT_WEBHOOK_URL}"

security:
  secret_key: "${SECRET_KEY}"
  algorithm: "HS256"
  access_token_expire_minutes: 15
  session_timeout_minutes: 30
  rate_limiting:
    enabled: true
    requests_per_minute: 1000
  encryption:
    enabled: true
    key: "${ENCRYPTION_KEY}"

external_services:
  pocket_option:
    base_url: "https://pocketoption.com"
    login_url: "https://pocketoption.com/en/login"
    trading_url: "https://pocketoption.com/en/cabinet/demo-quick-high-low/"
    websocket_url: "wss://pocketoption.com/ws/"
    timeout_seconds: 10
    retry_attempts: 5
    retry_delay_seconds: 2
    circuit_breaker:
      enabled: true
      failure_threshold: 5
      recovery_timeout: 60

testing:
  fixtures_path: "tests_new/fixtures/data"
  mock_external_services: false
  test_database_url: "${TEST_DATABASE_URL}"
  parallel_execution: true
  coverage_threshold: 90

deployment:
  container:
    image: "quantumflux:latest"
    port: 8000
    health_check_path: "/health"
  scaling:
    min_replicas: 2
    max_replicas: 10
    target_cpu_utilization: 70
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"